### PR TITLE
Fix Missing Performance Data

### LINKED ISSUE #77: The Performance_Activities and Performance_Machines worksheets are empty in the main data export
I'm pretty sure they are not meant to be!

### PR DESCRIPTION
**Pull request by dan-tang-ssd**
This PR is submitted to fix #77 

This PR contains below changes:
1. Add one-time command program to fill in missing performance activity and performance machine data

### CODE REVIEW

File: app/Console/Commands/AddMissingPerformanceData.php [hunk 1]
```diff
@@ -0,0 +1,119 @@
...
+        $this->info('Processing ' . count($mainSurveys) . ' main survey records...');
+
+        // remove all records from performance_activities and performance_machines tables
+        PerformanceActivity::truncate();
+        PerformanceMachine::truncate();
+
+        // handle all main survey records one by one
+        foreach ($mainSurveys as $mainSurvey) {
+            // find the corresponding submissions record
+            $submission = Submission::find($mainSurvey->submission_id);
```
Comment (dave-mills) [inline app/Console/Commands/AddMissingPerformanceData.php:46]: CPD comment: This works, but a better approach is to use the relationship already defined on the model: 

`$submission = $mainSurvey->submission;` 

Otherwise, we are essentially re-defining the relationship between MainSurvey and Submission here. By default, we should be using the relationships defined on the model classes (and if the relationship doesn't exist, we add it and then reference it). 

(And, while performance doesn't matter here, using the relationship means that we can use `$mainSurveys = MainSurvey::with('submission')->get();` at the top to avoid N+1 queries).

File: app/Console/Commands/AddMissingPerformanceData.php [hunk 2]
```diff
@@ -0,0 +1,119 @@
...
+                    $ac_num = $ac['ac_num'];
+                    $acname = $ac['ac_inner_grp']['acname'];
+                    $acname_other = $ac['ac_inner_grp']['acname_other'];
+                    $acrev = $ac['ac_inner_grp']['acrev'];
+                    $acrev_high_ack = $ac['ac_inner_grp']['acrev_high_ack'];
+                    $this->comment($mainSurvey->id . ' - ' . $submission->id);
+                    $this->comment($ac_num . ' - ' . $acname . ', ' . $acname_other . ', ' . $acrev . ', ' . $acrev_high_ack);
+
+                    $performanceActivity = $mainSurvey->performanceActivities()->create([
+                        'main_survey_id' => $mainSurvey->id,
```
Comment (dave-mills) [inline app/Console/Commands/AddMissingPerformanceData.php:71]: Good that you're using the relationship here to create the item. That means we don't need to add the `main_survey_id` manually.

File: app/Console/Commands/AddMissingPerformanceData.php [hunk 3]
```diff
@@ -0,0 +1,119 @@
...
+                    $machine_not_answer_note = $m['m_inner_grp']['machine_not_answer_note'];
+                    $mowned = $m['m_inner_grp']['mowned'];
+                    $mprice = $m['m_inner_grp']['mprice'];
+                    $myused = $m['m_inner_grp']['myused'];
+                    $myplan = $m['m_inner_grp']['myplan'];
+                    $this->comment($mainSurvey->id . ' - ' . $submission->id);
+                    $this->comment($m_number . ' - ' . $mname . ', ' . $machine_not_answer_note . ', ' . $mowned . ', ' . $mprice . ', ' . $myused . ', ' . $myplan);
+
+                    $performanceMachine = $mainSurvey->performanceMachines()->create([
+                        'main_survey_id' => $mainSurvey->id,
```
Comment (dave-mills) [inline app/Console/Commands/AddMissingPerformanceData.php:103]: As above

**Review by dave-mills — APPROVED** [review]
Looks good. Tested locally with live data, and the number of machines and activities records matches the results when downloading the raw data from ODK Central + filtering out the 'test' entries. 

I added some comments about  the use of relationships in the code; for future reference rather than required changes here.

**Comment by dan-tang-ssd** [comment]
Staging env deployment is completed.
Live env deployment is completed.

Execute one-time command program in both staging env and live env.
There are 0 and 129 main surveys processed in staging env and live env respectively.

Checked the added performance activities and performance machines data.
For submission 71, there are 11 performance activities but only first 3 records with data.
Crosschecked with ODK submission JSON content, there are 8 empty performance activities records.
I have removed them from live db.

Data extraction is working fine. Performance activities and performance machines data are showed in corresponding excel sheets.

I have manually copy the newly added missing performance data from the latest extracted excel file to our previously provided excel file with boolean columns.

Here is the excel file for reference:
[tape_data_export_with_booleans_and_gps_20240723.xlsx](https://github.com/user-attachments/files/16346097/tape_data_export_with_booleans_and_gps_20240723.xlsx)

---

Question:
1. Should we provide this latest excel file to Joe & FAO proactively? It seems better voice out before they ask about this. Empty sheet for performance activity and performance machine may really happen, even it is very unlikely that all survey without data for them. As we had a few issues for data extraction so far.... e.g. missing data for two columns (even it is not our fault...), data precision, add boolean columns, incorrect GPS data, etc. Probably we may need to do it a little bit carefully and skillfully to avoid affecting our image...
